<?php

namespace SymfoTweet\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * WallParamsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WallParamsRepository extends EntityRepository
{
}
