<?php

namespace SymfoTweet\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
use SymfoTweet\CoreBundle\Entity\WallModerate;

/**
 * WallModerateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WallModerateRepository extends EntityRepository
{
  public function getTweets($wall){
    return $this->findOneByWall($wall->getId());
  }

  public function getIdTweets($wall){
    $tweets_moderate = array();
    $query = $this->createQueryBuilder('wm')
      ->where('wm.wall = :wall_id')
      ->setParameter('wall_id',$wall->getId())
      ->getQuery();

    foreach($query->getResult() as $tweet){
      array_push($tweets_moderate,$tweet->getIdStr());
    }

    return $tweets_moderate;
  }

  public function addTweet($wall,$id_str){
    $tweet = $this->findOneBy(array(
      'wall' => $wall->getId(),
      'id_str' => $id_str
    ));

    if(!is_object($tweet)){
      $tweet = new WallModerate;
      $tweet->setWall($wall);
      $tweet->setIdStr($id_str);

      $this->_em->persist($tweet);
      $this->_em->flush();
    }
  }

  public function removeTweet($wall,$id_str){
    $tweet = $this->findOneBy(array(
      'wall' => $wall->getId(),
      'id_str' => $id_str
    ));

    if(is_object($tweet)){
      $this->_em->remove($tweet);
      $this->_em->flush();
    }
  }
}
