# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
services:
    core.twitter:
        class: SymfoTweet\CoreBundle\Service\Twitter
        arguments: ['%core.twitter.consumer_key%','%core.twitter.consumer_secret%']
